server:
  port: 10000
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
#        - id: gulimall-auth
#          uri: lb://gulimall-auth
#          predicates:
#            - Path=/auth/**