server:
  port: 10010
spring:
  cloud:
    gateway:
      routes:
        - id: meeting
          uri: lb://meeting
          predicates:
            - Path=/api/meeting/**
          filters:
            - RewritePath= /api/(?<segment>.*),/$\{segment}
        - id: auth
          uri: lb://auth
          predicates:
            - Path=/api/auth/**
          filters:
            - RewritePath= /api/(?<segment>.*),/$\{segment}
