server:
  port: 10010
spring:
  cloud:
    gateway:
      routes:
        - id: meeting
          uri: lb://meeting
          predicates:
            - Path=/meeting/*
        - id: auth
          uri: lb://auth
          predicates:
            - Path=/auth/*
