server:
  port: 10013

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://k423.xyz:3306/rjb_auth?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: rjb_auth
    password: ziM7SZhiAcmNkSDT
    hikari:
      maximum-pool-size: 12
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000
      connection-test-query: select 1
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql

  redis:
    timeout: 1000ms
    host: k423.xyz
    port: 6379
    database: 3
    password: CPa7Mn2ER8hDbrx6
  cache:
    type: redis
    redis:
      # 指定redis中的过期时间为1h
      time-to-live: 3600000
      #缓存空值
      cache-null-values: true
      use-key-prefix: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
file:
  upload:
    path: /home/rjb/upload/

oss:
  endpoint: https://oss-cn-beijing.aliyuncs.com
  access-key-id: LTAI5tRbacmb22t5b6XKxZcG
  access-key-secret: cvHsWCx5o3Uze7Q4pCo1xMkc1tinUI
  bucket-name: cocos-kepu
  object-name-prefix: ruanjianbei_2022/
  download-prefix: https://cocos-kepu.oss-cn-beijing.aliyuncs.com/ruanjianbei_2022/
  face-filename-prefix: FACE_
  face-filename-suffix: .png
face-compare:
  minimum-confidence: 0.8